platform :ios,'8.0'
target 'H98'do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'BaiduMapKit'
    pod 'GoogleMaps'
    pod 'Hero'
    pod 'SnapKit', '~> 3.2.0'#类似Masonry
    pod 'Alamofire'#类似AFN
end
